### PR TITLE
Logo corrected to match original logo

### PR DESCRIPTION
**Pull request by nikhiljohn10**
I have modifined the logo and wordmark to finely match with the original logo and wordmark provided in the resources.
screen capture 2014-08-22_21-24-22

### CODE REVIEW

**Comment by anushbmx** [comment]
Cool @nikhiljohn10 that looks great, will merget it

**Comment by anushbmx** [comment]
@nikhiljohn10  i see that you have used inline styles can you move it to css so it looks & feels good :)

**Comment by nikhiljohn10** [comment]
Ok

**Comment by nikhiljohn10** [comment]
The inline styles are moved in to the files.

**Comment by anushbmx** [comment]
@nikhiljohn10 auto merge is not working I will mannually merge it later, the maker party is keeping me engaged all time.

**Pull request closed without merging**
